name: release
on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: macos-12
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - uses: ./.github/actions/release
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        signing-identifier: ${{ secrets.SIGNING_IDENTIFIER }}
        apple-id: ${{ secrets.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
        team-id: ${{ secrets.TEAM_ID }}
        certificate-base64: ${{ secrets.CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}