name: tagpr
on:
  push:
    branches:
    - "main"
jobs:
  tagpr:
    runs-on: macos-12
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ./.github/actions/release
      with:
        tag: ${{ steps.tagpr.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}
        signing-identifier: ${{ secrets.SIGNING_IDENTIFIER }}
        apple-id: ${{ secrets.APPLE_ID }}
        apple-id-password: ${{ secrets.APPLE_ID_PASSWORD }}
        team-id: ${{ secrets.TEAM_ID }}
        certificate-base64: ${{ secrets.CERTIFICATE_BASE64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
      if: "steps.tagpr.outputs.tag != ''"
